[package]
name = "gl0"
version = "0.1.0"
authors = ["JongChan Choi <jong@chan.moe>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
euclid = "0.20"
gl = "0.14.0"
surfman = "0.3.0"
